### ISSUE TITLE
Tool accessor notebook has wrong test data file path

### ISSUE THREAD

**Issue by rywm-dhi** [DHI/mikepluspy#13]
![image](https://github.com/DHI/mikeplus-python/assets/74630349/218d982d-4a4e-440b-8bb4-1cd6fefac486)

**Comment by PanDan0620** [comment]
Verify pass. Now test data was updated in ToolsAccessor.ipynb

**Comment by wuwwen** [comment]
@rywm-dhi This has been fixed on Dev branch. I just close this one now.
