### ISSUE TITLE
Setting the value of a database does not auto cast values

### ISSUE THREAD

**Issue by ryan-kipawa** [DHI/mikepluspy#14]
The code below demonstrates the issue. Here, a user tries to update the upstream invert to a value of 50.0, but they neglect the decimal by instead using an integer. There is no warning or error in Python, yet nothing happens on the database side.

```python
values = {'UpstreamInvert': 50, 'Description': 'setValues'}
data_access.set_values("msm_Culvert", "bridge1", values)
```

**Comment by PanDan0620** [comment]
Verify pass with MIKE+ Development branch 2004.03.29
