### ISSUE TITLE
Insert fails silently when no value is provided for 'Seq'

### ISSUE THREAD

**Issue by ryan-kipawa** [DHI/mikepluspy#19]
If you try to insert a new record as follows, nothing is added, and no error is caught:
```python
from mikeplus import DataTableAccess
dta = DataTableAccess("mymodel.sqlite")
dta.insert("msm_Project", "Some new simulation")
``` 
This seems to be due to the 'Seq' field being required. So there's two main issues:

1. How to catch errors from the Python side when they happen.
2. How to handle the 'Seq' field for relevant tables.

**Comment by PanDan0620** [comment]
Verify pass with MIKE+ Development branch.

**Comment by PanDan0620** [comment]
Verify pass with MIKE+ Development branch

**Comment by otzi5300** [comment]
fixed
