### ISSUE TITLE
Some field names in the sqlite database have Nullable types that's awkward to handle in Python

### ISSUE THREAD

**Issue by ryan-kipawa** [DHI/mikepluspy#20]
Here's an example of the issue:
https://github.com/DHI/mikepluspy/blob/891dfbec466b20ec3267a68232a0464766bdd9f2/notebooks/run_multiple_rainfall_events.ipynb#L200-L202
The preferred syntax would be for python integers to work, without needing to wrap them in System.Nullable.

**Comment by ecomodeller** [comment]
Isn't that the job of this library. The user supplies a value, either an int or None, and `mikepluspy` translates it to a .NET nullable int if if goes through a .NET DAL?

**Comment by PanDan0620** [comment]
Verify pass with MIKE+ Development branch 2004.03.29. 
Now we can modify the test script:
"         VariationNo = 3, # set temporal variation to timeseries\n", 
 "        FlowTypeNo = 5, # set boundary condition type to Rainfall\n", 
 "        LoadTypeNo = 1, # set load type to stormwater runoff\n",
