### ISSUE TITLE
MIKE+ 2024 update 1 version of mikepluspy install error

### ISSUE THREAD

**Issue by lizaclark** [DHI/mikepluspy#40]
I was previously able to use mikepluspy version 2024.0.0 with MIKE+ 2024. I recently upgraded to MIKE+ 2024 Update 1. After this, mikepluspy returned the ImportError message in the screenshot below. I can work around this temporarily by commenting out `from .epanet import EPANET` in `__init__.py`.

I saw on the GitHub site that a newer version of mikepluspy is available. I tried uninstalling the previous version then following the install instructions: `pip install https://github.com/DHI/mikepluspy/archive/refs/tags/v2024.1-latest.zip`. This returns an error message: "ERROR: HTTP error 404 while getting https://github.com/DHI/mikepluspy/archive/refs/tags/v2024.1-latest.zip
ERROR: Could not install requirement https://github.com/DHI/mikepluspy/archive/refs/tags/v2024.1-latest.zip because of HTTP error 404 Client Error: Not Found for url: https://codeload.github.com/DHI/mikepluspy/zip/refs/tags/v2024.1-latest for URL https://github.com/DHI/mikepluspy/archive/refs/tags/v2024.1-latest.zip". Is it possible to install this another way?

![image](https://github.com/DHI/mikepluspy/assets/5132040/4c9f1d47-5e28-4f29-98f8-baf9fe893df2)

**Comment by lizaclark** [comment]
Only v2024.0.0 shows up on github under releases. I don't see v2024.1.
![image](https://github.com/DHI/mikepluspy/assets/5132040/a3767da4-103f-4ead-a613-e8f209500db5)

**Comment by wuwwen** [comment]
Dear @lizaclark mikepluspy 2024.1 is not available yet. It's still on the way. It properly be ready next week. I'll let you know the when is available to download.

**Comment by otzi5300** [comment]
Release 2024.1 is now available. It is compatible with MIKE+ 2024 Update 1. 

@lizaclark try pip install https://github.com/DHI/mikepluspy/archive/refs/tags/v2024.1-latest.zip

**Comment by lizaclark** [comment]
@otzi5300 and @wuwwen - thank you for your responses. I was able to install release 2024.1 today
