### ISSUE TITLE
Clarify how to read and modify scenarios

### ISSUE THREAD

**Issue by ryan-kipawa** [DHI/mikepluspy#53]
More clear guidance is required for working with scenarios (and perhaps a simplified API).

Related issues/discussions:
#52 
#42 

I suggest the following:

- [ ] #55
- [x] #54
    - How to list available scenarios and check active scenario
    - How to filter queries by a specific scenario (default use active?)
    - How to modify the right scenario when updating or inserting values (default use active?)
    - How to change the active scenario
- [ ] Explore how working with scenarios could be made easier if the above notebook is too verbose

**Comment by wuwwen** [comment]
Nodebook has been added. This issue can be closed.
