### ISSUE TITLE
Add a notebook example showing how to work with scenarios in the current form

### ISSUE THREAD

**Issue by ryan-kipawa** [DHI/mikepluspy#54]
- How to list available scenarios and check active scenario
- How to filter queries by a specific scenario (default use active?)
- How to modify the right scenario when updating or inserting values (default use active?)
- How to change the active scenario

**Comment by wuwwen** [comment]
This is not just a notebook task. We need to implement relative methods in the package.

**Comment by ryan-kipawa** [comment]
> This is not just a notebook task. We need to implement relative methods in the package.

Ok thanks for clarifying that. I've opened a new issue to focus on identifying and implementing those methods #55
